using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SplineMesh {
    public class EnigmaRail : MonoBehaviour
    {
        public Spline rail;   
        public float railHeight;
        [Range(0,1f)]
        public float friction;
        [Range(0,1)]
        public float handling;

        [Header("Test")]
            public Transform projectReference;
            public Transform projectedObject;

        Transform sower;

        // Start is called before the first frame update
        void Start()
        {
            
        }

        // Update is called once per frame
        void FixedUpdate()
        {
            ExampleSower sowerScript = rail.gameObject.GetComponent<ExampleSower>();
            if(sowerScript != null)
            {
                sower = rail.transform.Find("generated by ExampleSower");
                sower.GetChild(sower.childCount-1).gameObject.SetActive(false);
            }

            /*
            if(projectReference != null && projectedObject != null)
            {
                CurveSample sample = rail.GetProjectionSample( transform.InverseTransformPoint(projectReference.position) );
                projectedObject.position = transform.position + sample.location;
                projectedObject.rotation = sample.Rotation;
            }*/
        }
    }
}